extends: substitution
message: "Use the STE-Code American spelling '%s' instead of '%s'."
level: error
ignorecase: true
swap:
  analyse: analyze
  analysed: analyzed
  analysing: analyzing
  analyser: analyzer
  analysers: analyzers
  authorise: authorize
  authorises: authorizes
  authorised: authorized
  authorising: authorizing
  behaviour: behavior
  behaviours: behaviors
  calibre: caliber
  cancelled: canceled
  cancelling: canceling
  catalogue: catalog
  catalogued: cataloged
  cataloguing: cataloging
  centre: center
  centred: centered
  centres: centers
  colour: color
  coloured: colored
  colouring: coloring
  colours: colors
  customise: customize
  customises: customizes
  customised: customized
  customising: customizing
  defence: defense
  flavour: flavor
  flavours: flavors
  fibre: fiber
  fibres: fibers
  harbour: harbor
  harbours: harbors
  honour: honor
  honours: honors
  initialise: initialize
  initialises: initializes
  initialised: initialized
  initialising: initializing
  judgement: judgment
  labelled: labeled
  labelling: labeling
  labour: labor
  licence: license
  litre: liter
  litres: liters
  modelled: modeled
  modelling: modeling
  neighbour: neighbor
  neighbours: neighbors
  normalise: normalize
  normalises: normalizes
  normalised: normalized
  normalising: normalizing
  optimise: optimize
  optimises: optimizes
  optimised: optimized
  optimising: optimizing
  organise: organize
  organises: organizes
  organised: organized
  organising: organizing
  parameterise: parameterize
  parameterises: parameterizes
  parameterised: parameterized
  parameterising: parameterizing
  parametrise: parameterize
  parametrises: parameterizes
  parametrised: parameterized
  parametrising: parameterizing
  practise: practice
  programme: program
  programmes: programs
  recognise: recognize
  recognises: recognizes
  recognised: recognized
  recognising: recognizing
  rigour: rigor
  rumour: rumor
  rumours: rumors
  serialise: serialize
  serialises: serializes
  serialised: serialized
  serialising: serializing
  signalled: signaled
  signalling: signaling
  standardise: standardize
  standardises: standardizes
  standardised: standardized
  standardising: standardizing
  synchronise: synchronize
  synchronises: synchronizes
  synchronised: synchronized
  synchronising: synchronizing
  theatre: theater
  theatres: theaters
  travelled: traveled
  traveller: traveler
  travellers: travelers
  travelling: traveling
  vapour: vapor
